### ISSUE TITLE
Cannot set lower and higher values programatically...

### ISSUE THREAD

**Issue by iHirenDev** [mikeplatt/MJPSlider#1]
Hello,
I am using MJPSlider in my app.
I want to set the lower and higher values as per the server response programatically.
I used 
-  -(void)setLowerValue:(CGFloat)lowerValue andUpperValue:(CGFloat)upperValue animated:(BOOL)animated,

mySlider.lowerValue,mySlider.higherValue,mySlider.minValue,mySlider.maxValue.
But I am still not able to set the values.
What should I do for setting the slider values?

**Comment by mikeplatt** [comment]
Make sure you have set the minValue and maxValue before setting lowerValue and upperValue (ensure that min <= lower and max >= upper).
